name: Deploy Poopdeck Pirates

on:
  release:
    types: published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute remote commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/pirategame
            git pull origin main
            npm install
            npm run build:all
            
            # restart/start pm2
            pm2 restart poopdeck-server || \
            pm2 start server/built/server.js \
            --name "poopdeck-server" \
            --node-args="-r tsconfig-paths/register" \
            --cwd /home/pirategame
            pm2 save
